ProfilePlatform/ProfilePlatform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('user/',include('user.urls'))
]+ static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

ProfilePlatform/main/urls.py
from django.urls import path
from .import views
app_name = 'main'

urlpatterns =[
    path('',views.home_view, name='home_view'),
    path('profile/<user_id>/',views.profile_view,name='profile_view')
    
]

ProfilePlatform/user/urls.py
from django.urls import path
from .import views

app_name = 'user'

urlpatterns =[
    path('register/',views.register_view, name='register_view'),
    path('login/',views.log_in_view,name ='log_in_view'),
    path('logout/',views.logout_view,name='logout_view'),
    path('add/education',views.add_education,name= 'add_education'),
    path('add/skill/',views.add_skill,name='add_skill'),
    path('update/profile/<user_id>/',views.update_profile,name='update_profile'),
    path('delete/education/',views.delete_education_view,name='delete_education_view'),
    path('delete/skill/',views.delete_skill, name='delete_skill'),
    path("contact/",views.contact_view,name="contact_view"),
    path("add/course/",views.add_course , name="add_course"),
    path("delete/course/",views.delete_course_view,name="delete_course_view")
]

ProfilePlatform/user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Profile(models.Model):
    
    user = models.OneToOneField(User,on_delete = models.CASCADE)
    avatar = models.ImageField(upload_to='images/',default='images/default.jpg')
    phone_number = models.IntegerField(default=0)
    bio = models.TextField()
    career = models.CharField(max_length=255)
    linkedin = models.URLField()
    github = models.URLField()

    def __str__(self) -> str:
        return self.user.username



class Education(models.Model):

    user = models.ForeignKey(User,on_delete = models.CASCADE)
    qualifications = models.TextChoices('qualifications',['None','Diploma','Bachelor','Doctorate'])
    qualification = models.CharField(max_length=56,choices = qualifications.choices, default='None')
    start_year = models.DateField()
    end_year = models.DateField()
    specialization = models.CharField(max_length = 255)
    university_name = models.CharField(max_length = 255)


    def __str__(self) -> str:
        return self.user.username

class Skill(models.Model):

    user = models.ForeignKey(User,on_delete = models.CASCADE)
    skill = models.CharField(max_length = 255)
    proficiency_rate =models.IntegerField()

    

    def __str__(self) -> str:
        return self.user.username
    



class Course(models.Model):
    user = models.ForeignKey(User,on_delete = models.CASCADE)
    title = models.CharField(max_length = 255)
    description = models.TextField()
    hour = models.IntegerField(default=0)

    def __str__(self) -> str:
        return self.title

ProfilePlatform/user/views.py
from django.shortcuts import render,redirect
from django.http import HttpRequest,HttpResponse
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login, logout
from .models import Education,Skill, Profile,Course
from django.core.mail import send_mail
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib import messages
# Create your views here.

def send_custom_email(to_email, subject, message):
    send_mail(
        subject,
        message,
        settings.EMAIL_HOST_USER,
        [to_email],
        fail_silently=False,
    )


def register_view(request:HttpRequest):
    if request.method == 'POST':
        user =User.objects.create_user(username=request.POST['username'],email=request.POST['email'],password=request.POST['password'])
        user.save()
        return redirect('main:home_view')
    return render(request,'user/register.html')




def log_in_view(request:HttpRequest):
    msg=None
    if not request.user.is_authenticated:
        if request.method == 'POST':
            user = authenticate(username =request.POST['username'],password = request.POST['password'])

            if user:
                login(request,user)
                return redirect('main:home_view')
            else:
                msg="please inter correct username and password"
    else:
        return redirect('main:home_view')
    return render(request,'user/login.html',{'msg':msg})


def logout_view(request:HttpRequest):

    if request.user.is_authenticated:
        logout(request)
        return redirect('user:log_in_view')

@login_required
def update_profile(request:HttpRequest,user_id):
    user = User.objects.get(id=user_id)
    try:

        profile = user.profile
    except:
        profile = Profile(user=user)
    
    if request.user.is_authenticated and user.id == request.user.id:

        if request.method == 'POST':
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.email = request.POST['email']
            user.save()
            if 'avatar' in request.FILES:
                profile.avatar = request.FILES['avatar']
            profile.bio = request.POST['bio']
            profile.career = request.POST['career']
            profile.linkedin = request.POST['linkedin']
            profile.github = request.POST['github']
            profile.phone_number = request.POST["phone_number"]
            profile.save()
            messages.success(request, "Your profile was updated successfully!")
                
            #return redirect('main:profile_view',user_id)
    
    return render(request,'user/update_profile.html')

@login_required
def add_education(request:HttpRequest):

    user = request.user
    education = Education(user = user)

    if request.method == 'POST':
        education.qualification = request.POST['qualification']
        education.start_year = request.POST['start_year']
        education.end_year = request.POST['end_year']
        education.specialization = request.POST['specialization']
        education.university_name = request.POST['university_name']
        education.save()

        return redirect('main:profile_view',user.id)
    
@login_required
def delete_education_view(request:HttpRequest):
    
    
    if request.user.is_authenticated:
        if request.POST:

            education = Education.objects.get(id = request.POST["education-id"])


            education.delete()
        return redirect('main:profile_view',request.user.id)




@login_required
def add_skill(request:HttpRequest):

    user = request.user
    skill = Skill(user=user)
    if request.method == 'POST':
        proficiency_rate_to_int =int(request.POST['proficiency_rate'])
        skill.skill=request.POST['skill']
        skill.proficiency_rate= proficiency_rate_to_int
        skill.save()
        
        return redirect('main:profile_view',user.id)
@login_required    
def delete_skill(request:HttpRequest):
    if request.method == 'POST':
        skill_id = request.POST['skill-id']
        
        skill = Skill.objects.get(id=skill_id)

        if request.user.is_authenticated:

         skill.delete()

    return redirect('main:profile_view',request.user.id)



def contact_view(request:HttpRequest):

    if request.method == 'POST':
        to_email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')
        send_custom_email(to_email, subject, message)
        return HttpResponse("Email sent successfully!")

    return render(request,"user/contact.html")


@login_required
def add_course(request:HttpRequest):

    
    course = Course(user = request.user)

    if request.method == "POST":

        course.title = request.POST["title"]
        course.description = request.POST["description"]
        course.hour = request.POST["hour"]

        course.save()

        return redirect('main:profile_view',request.user.id)
    



@login_required
def delete_course_view(request:HttpRequest):

    if request.method == "POST":
    
        course = Course.objects.get(id= request.POST["course-id"])

        course.delete()

        return redirect('main:profile_view',request.user.id)

ProfilePlatform/user/templates/user/contact.html
{% extends "main/base.html" %}

{% load static %}


{% block content %}

<div>
    <form method="post" action="{% url 'user:contact_view' %}">
        {% csrf_token %}
        <label for="email">To Email:</label>
        <input type="email" id="email" name="email" required><br><br>
        <label for="subject">Subject:</label>
        <input type="text" id="subject" name="subject" required><br><br>
        <label for="message">Message:</label>
        <textarea name="message" id=""></textarea>
        <button type="submit" >send</button>
        </form>
</div>

{% endblock %}

ProfilePlatform/user/templates/user/login.html
{% extends 'main/base.html' %}



{% block title %}Log in{% endblock %}


{% block content %}

<div class="container vh-100">
    <div class="row">
        {% if msg %}
        <div class="art">
            <p>{{msg}}</p>
        </div>
        {% endif %}
        <div class="col">
            <form class="form-control" method="post" action="{% url 'user:log_in_view'%}">
                {% csrf_token %}
                <div>
                    <label  for="">Username</label>
                    <input class="form-control" type="text" name="username" placeholder="username" required >
                </div>
                <div>
                    <label  for="">Password</label>
                    <input class="form-control" type="password" name="password"  required minlength="6">
                </div>
                <button class="btn btn-primary mt-3" type="submit">Register</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

ProfilePlatform/user/templates/user/register.html
{% extends 'main/base.html' %}



{% block title %}Register{% endblock %}


{% block content %}

<div class="container">
    <div class="row">
        <div class="col">
            <form class="form-control" method="post" action="{% url 'user:register_view'%}">
                {% csrf_token %}
                <div>
                    <label  for="">Username</label>
                    <input class="form-control" type="text" name="username" placeholder="username" required minlength="6">
                </div>
                <div >
                    <label  for="">Email</label>
                    <input class="form-control" type="email" name="email" placeholder="@gmail.com" required>
                </div>
                <div>
                    <label  for="">Password</label>
                    <input class="form-control" type="password" name="password"  required minlength="6">
                </div>
                <button class="btn btn-primary mt-3" type="submit">Register</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

ProfilePlatform/user/templates/user/update_profile.html
{% extends 'main/base.html'%}



{% block title %}Update Profile{% endblock %}

{% block content %}

<div class="container">
    <div class="row">

        <div class="col-12">

                    <!-- Bootstrap Modal -->
<div class="modal fade" id="messageModal" tabindex="-1" aria-labelledby="messageModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="messageModalLabel">Message</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <!-- Messages Content -->
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{ message.tags }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
            <form class="row" action="{% url 'user:update_profile' request.user.id %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="col-4" >
                    <label for="">First Name:</label>
                    <input class="form-control" type="text" name="first_name" required value="{{user.first_name}}">
                </div> 

                <div class="col-4" >
                    <label for="">Last Name:</label>
                    <input class="form-control" type="text" required name="last_name" value="{{user.last_name}}">
                </div>

                <div class="col-4" >
                    <label for="">Email:</label>
                    <input class="form-control" type="email" name="email" required value="{{user.email}}">
                </div>



                <div class="col-4"  >
                    <label for="">Avatar:</label>
                    <input class="form-control" type="file" name="avatar" >
                </div>
                <div class="col-4">
                    <label for="phone_number">Phone Number:</label>
                    <div class="input-group">
                        <div class="input-group-prepend">
                            <span class="input-group-text">+966</span>
                        </div>
                        <input class="form-control" type="number" name="phone_number" max="9999999999" required value="{{user.profile.phone_number}}">
                    </div>
                </div>
                
                

                <div class="col-4" >
                    <label for="">Career:</label>
                    <input class="form-control" type="text" name="career" required value="{{user.profile.career}}" >
                </div>

                <div class="col-4" >
                    <label for="">Lnkedin Link:</label>
                    <input class="form-control" type="url" name="linkedin" required value="{{user.profile.linkedin}}" >
                </div>

                <div class="col-4"  >
                    <label for="">GitHub Link:</label>
                    <input class="form-control" type="url" name="github" required value="{{user.profile.github}}">
                </div>
                <div class="col-4" >
                    <label for="">Bio:</label>
                    <textarea class="form-control" name="bio" id="" cols="30" rows="10">{{user.profile.bio}}</textarea>
                </div> 

                <button type="submit" class="btn btn-primary">Update</button>
                
            </form>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            {% if messages %}
                var messageModal = new bootstrap.Modal(document.getElementById('messageModal'));
                messageModal.show();
            {% endif %}
        });
    </script>
    
</div>


{% endblock %}